# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Deploy

on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: "Default version to use when preparing a release."
        required: true
        default: "X.Y.Z"
      developmentVersion:
        description: "Default version to use for new local working copy."
        required: true
        default: "X.Y.Z-SNAPSHOT"

jobs:
  build:

    runs-on: ubuntu-latest
    environment: deploy
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-package: 'jdk'
        java-version: '11'
        server-id: 'alex9849-nexus'
        server-username: NEXUS_USERNAME
        server-password: NEXUS_PASSWORD
        gpg-private-key: ${{ secrets.MAVEN_PGP_SECRET_KEY }}
        gpg-passphrase: MAVEN_PGP_PASSPHRASE

    - name: Configure Git User
      run: |
        git config user.email "actions@github.com"
        git config user.name "GitHub Actions"

    - name: Maven Release
      run: mvn --no-transfer-progress --batch-mode clean release:prepare release:perform -B -DreleaseVersion=${{ github.event.inputs.releaseVersion }} -DdevelopmentVersion=${{ github.event.inputs.developmentVersion }}
      env:
        GITHUB_TOKEN: ${{ secrets.REPO_WRITE_TOKEN }}
        MAVEN_PGP_PASSPHRASE: ${{ secrets.MAVEN_PGP_PASSPHRASE }}
        NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
        NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.event.inputs.releaseVersion }}
        release_name: ${{ github.event.inputs.releaseVersion }}
